[project]
# Whether to enable telemetry (default: true). No personal data is collected.
enable_telemetry = true

# List of environment variables to be provided by each user to use the app.
user_env = []

# Duration (in seconds) during which the session is saved when the connection is lost
session_timeout = 3600

# Duration (in seconds) of the user session expiry
user_session_timeout = 86400   # 1 day

# Enable third parties caching (e.g LangChain cache)
cache = false

# Authorized origins (seguridad mejorada: especifica dominios si es producción)
# allow_origins = ["https://mapfre.es"]  # Cambia "*" por dominios específicos si es posible

# Language setting
language = "es"

[features]
# Process and display HTML in messages. This can be a security risk
unsafe_allow_html = false

# Process and display mathematical expressions (set to true if using LaTeX)
latex = false

# Automatically tag threads with the current chat profile
auto_tag_thread = true

# Allow users to edit their own messages
edit_message = true

# Authorize users to spontaneously upload files with messages
[features.spontaneous_file_upload]
enabled = true
accept = ["image/*", "application/pdf"]  # Acepta solo imágenes y PDFs por seguridad
max_files = 5
max_size_mb = 500  # Se puede reducir a 100MB para evitar sobrecarga del servidor

[features.audio]
# Sample rate of the audio (opción recomendada 24000 o 44100)
sample_rate = 24000

[UI]
# Name of the assistant.
name = "MAPPI"

# Default theme ("light" o "dark")
default_theme = "light"

# Layout configuration
layout = "wide"

# Description of the assistant (útil para SEO y accesibilidad)
description = "Esta es nuestra propuesta de RAG para la aseguradora Mapfre de nuestro TFM"

# Chain of Thought (CoT) display mode. Can be "hidden", "tool_call" or "full".
cot = "hidden"

# Link to your GitHub repo (descomentar si tienes repositorio público)
# github = ""https://github.com/ssillerom/tfm_valley_2025_g3"

# Specify a CSS file to customize the user interface.
custom_css = "/public/stylesheet.css"  # Descomentado para aplicar estilos personalizados

# Specify a Javascript file to customize the user interface.
# custom_js = "/public/focus.js"


# Specify a custom meta image url.
custom_meta_image_url = "https://s3-symbol-logo.tradingview.com/mapfre--600.png"

# Specify a custom build directory for the frontend.
# custom_build = "./public/build"

[meta]
generated_by = "2.0.1"
